openapi: 3.2.0
info:
  title: PixieBrix Proxy API
  version: 1.0.0
  description: PixieBrix admin and package registry API
  contact:
    name: PixieBrix Support
    email: support@pixiebrix.com
servers:
- url: https://app.pixiebrix.com
tags:
- name: proxy
paths:
  /api/proxy/:
    post:
      operationId: createRequestProxy
      description: API authentication proxy.
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json; version=1.0:
              schema: {}
            application/vnd.pixiebrix.api+json; version=1.0:
              schema: {}
          description: ''
      tags:
      - proxy
